### ISSUE TITLE
Room upgrade support

### ISSUE THREAD

**Issue by non-Jedi** [alphapapa/matrix-client.el#101]
Because this client doesn't implement [the newish room upgrades part of the spec](https://matrix.org/docs/spec/client_server/r0.6.1#id160), I have 4 or 5 versions of the same room cluttering up my buffer list and have to manually figure out which is which. I know this isn't a high priority to implement, but I thought I should open an issue tracking the feature anyway (and in case I unexpectedly get some time to hack on this client and want to implement it myself).

**Comment by alphapapa** [comment]
Yeah, the current version of the client was mostly written targeting the r0.3.0 API spec.  There are many changes between it and the current version of the spec.  Matrix still seems like a rapidly moving target, and it will be a lot of work to bring this client up-to-date with it.  And the amount of state that clients are expected to track makes it difficult to cleanly separate API from implementation in the client.  So my enthusiasm for keeping this client up-to-date has waned.  I'm glad it still functions as well as it does.

Fixing or working around this specific issue might not be too difficult, if it's just a matter of not displaying buffers for rooms with tombstone events.

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
