### ISSUE TITLE
Consider using LUI for our UI

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/matrix-client.el#15]
It's used by Circe and the Emacs Slack client.  Could save us a lot of work.

**Comment by alphapapa** [comment]
Jorgen said that he's open to the idea, and he added it to Circe's 2.7 milestone:

> Hello, and thanks for the suggestion! Support for deletion of messages is rather new, and introduced the message ID concept at all. I don't see a reason not to support updating or out of order insertion now as well. :-)

**Comment by catern** [comment]
Just as one datapoint, if matrix-client.el used LUI I would be much more likely to use matrix-client.el. I already use and like LUI for Circe, and it would be nice to avoid having to configure two different Emacs chat UIs to my tastes.

**Comment by alphapapa** [comment]
@catern Okay, but FYI, I don't intend to rewrite this client to use LUI.  It would be a tremendous amount of work for little benefit at this point, and would require reimplementing some features as well.

If you don't like this client's UI, you might look at https://github.com/alphapapa/ement.el, which is an alternative client I've made.  It doesn't use LUI either, though.

**Comment by Thaodan** [comment]
>If you don't like this client's UI, you might look at https://github.com/alphapapa/ement.el, which is an alternative client I've made. It doesn't use LUI either, though.

That doesn't really trustful having two clients on such a big task that is already hard enough.

**Comment by alphapapa** [comment]
> > If you don't like this client's UI, you might look at https://github.com/alphapapa/ement.el, which is an alternative client I've made. It doesn't use LUI either, though.
> 
> That doesn't really trustful having two clients on such a big task that is already hard enough.

Huh?

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
