### ISSUE TITLE
Access tokens and passwords may be revealed by curl

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/matrix-client.el#25]
@jgkamat I guess there's nothing we can do about this, and it's upstream of us anyway, being in `request` and `curl`.  But when `request` is using curl, there is a risk that passwords and access tokens may be revealed by temporary files (sometimes they seem to be left behind in `/tmp`, but I'm not sure when/why), and command line args (i.e. command-line args are visible to all processes on the system, regardless of user ID).  If we ever publish this package, we should probably at least note this prominently in the readme, so users can decide if they want to take the risk.  I'm not worried about it on my system, but I would want to be informed if I were a user.

Maybe we should also consider reporting a bug on `request`, in case it can be fixed.  If the GET params could always be passed with a file instead of args, that would fix half of it.  Then maybe we could figure out why sometimes temp files are left behind, and/or ensure that they are created 0600.

Another possibility would be to investigate `url-retrieve`, which is built in to Emacs and supports async.  But I don't think it has nearly as many useful features as `request`.  However, from what I can tell, it does not use curl but Emacs's native network support, so it might not have these issues (or it might, I really don't know).

**Comment by jgkamat** [comment]
According to [this line of request.el](https://github.com/tkf/emacs-request/blob/master/request.el#L709), this looks like a bug in request (those files look like they should be cleaned up), but there is a fixme present. We could look into which cases trigger this, and ensure cleanup happens.

**Comment by alphapapa** [comment]
Well, that's one possibility.  I'm not eager to dig into the `request` code myself.  :)  I wonder if it's still necessary to use it, i.e. I wonder if `url.el` is still problematic enough to need `curl` as a backend.  I know `url.el` supports `async`, but I'm guessing that that spawns external Emacs processes...which I guess would be "heavier" than external `curl` processes...but they would be like `emacs -q` processes, so is that necessarily a problem?

What do you think?  I might play with using `url-retrieve` and see how hard it would be to switch...

**Comment by jgkamat** [comment]
`url.el` definetly can be used as a replacement, but we have to be pretty careful about how we use that as well. We'd need to make sure we [don't leave url buffers hanging around](https://github.com/magit/ghub/issues/30), and maybe a couple other concerns as well. We have to spend a bit of time making sure we get this right regardless :P.

**Comment by alphapapa** [comment]
Good call.  I use `url-retrieve` in `org-web-tools`, and I have a line that explicitly kills the buffers, but I wasn't sure if it was necessary.  Now I know that it is.  :)

**Comment by alphapapa** [comment]
I feel like there should be a convenience wrapper for `url` that makes it easy to do the right thing.  Here's a start.  It uses `with-gensyms*` from my yet-to-be-published https://github.com/alphapapa/elexandria/blob/master/elexandria.el#L121

```el
(cl-defmacro with-url-retrieve-sync (url silent inhibit-cookies &rest body)
  (declare (indent defun))
  `(with-gensyms* (response-buffer headers response)
     (let* ((response-buffer (url-retrieve-synchronously ,url ,silent ,inhibit-cookies))
            headers response)
       (with-current-buffer response-buffer
         (setq headers (buffer-substring (point) url-http-end-of-headers)
               response (buffer-substring url-http-end-of-headers (point-max))))
       (unless (kill-buffer response-buffer)
         (warn "Unable to kill response buffer: %s" response-buffer))
       ,@body)))

(with-url-retrieve-sync "https://github.com/jgkamat/matrix-client-el" 'silent 'inhibit-cookies
  (message response))
```

**Comment by alphapapa** [comment]
For async, I think this is pretty nice to use:
```el
(cl-defmacro with-url-retrieve-async (url &key success cbargs silent inhibit-cookies data method extra-headers error)
  "Retrieve URL with `url-retrieve'.

Arguments SILENT, and INHIBIT-COOKIES are passed to
`url-retrieve', which see.

DATA is bound to `url-request-data', which see.

METHOD is bound to `url-request-method', which see.

EXTRA-HEADERS is bound to `url-request-extra-headers', which see.

SUCCESS may be a function symbol or a body form, which will be
called upon successful completion of the request.  In the call to
SUCCESS, these variables will be bound:

`status': See `url-retrieve'.
`cbargs': See `url-retrieve'.
`headers': The HTTP response headers.
`body': The HTTP response body.

ERROR may be a function symbol or a body form.  In the error
call, these variables will be bound, in addition to the ones
bound for SUCCESS:

`errors': The list of `url' error symbols for the most recent
error, e.g. `(error http 404)' for an HTTP 404 error.

In the SUCCESS and ERROR calls, the current buffer will be the
response buffer, and it will be automatically killed when the
call completes."
  (declare (indent defun))
  (with-gensyms* (success-body-fn error-body-fn)
    (let ((success-body-fn (cl-typecase success
                             (function success)
                             (otherwise `(lambda ()
                                           ,success))))
          (error-body-fn (cl-typecase error
                           (function error)
                           (otherwise `(lambda ()
                                         (let ((errors (plist-get status :error)))
                                           ,error))))))
      `(let* ((url-request-data ,data)
              (url-request-method ,method)
              (url-request-extra-headers ,extra-headers)
              ( success (cl-function
                         (lambda (status &rest cbargs)
                           (unwind-protect
                               ;; This is called with the current buffer already being the response buffer.
                               (let ((headers (buffer-substring (point) url-http-end-of-headers))
                                     (body (buffer-substring (1+ url-http-end-of-headers) (point-max))))
                                 ;; Check for errors
                                 (pcase status
                                   (`(:error . ,_) (funcall ,error-body-fn))
                                   (_ (funcall ,success-body-fn))))
                             (unless (kill-buffer (current-buffer))
                               (warn "Unable to kill response buffer: %s" (current-buffer))))))))
         (url-retrieve ,url success ,cbargs ,silent ,inhibit-cookies)))))
```

Used like:
```el
(with-url-retrieve-async "https://github.com/jgkamat/matrix-client-el"
  :cbargs '(123)
  :success (message "\n\nSUCCESS %s" (list :buffer (current-buffer)
                                           :status status
                                           :cbargs cbargs
                                           :headers headers
                                           :body body))
  :error (message "\n\nERROR: %s" (list :buffer (current-buffer)
                                        :status status
                                        :cbargs cbargs
                                        :headers headers
                                        :body body
                                        :error errors)))

(with-url-retrieve-async "https://github.com/jgkamat/matrix-client-el/404-not-found"
  :cbargs '(123)
  :success (message "\n\nSUCCESS %s" (list :buffer (current-buffer)
                                           :status status
                                           :cbargs cbargs
                                           :headers headers
                                           :body body))
  :error (message "\n\nERROR: %s" (list :buffer (current-buffer)
                                        :status status
                                        :cbargs cbargs
                                        :headers headers
                                        :body body
                                        :error errors)))
```
What do you think?  Probably needs some more tweaking if we actually start to use it, but it seems nicer than doing everything manually, and the response buffers *should* always be killed this way.

**Comment by alphapapa** [comment]
Note, current version of this macro (now a function) is at https://github.com/alphapapa/elexandria/blob/master/elexandria.el#L187.

**Comment by alphapapa** [comment]
Closing since we use url.el for everything except uploading files now.

**Comment by alphapapa** [comment]
It seems to me that since we do use `request` with `curl` for uploading files, this may still be an issue.  I don't remember why I closed this issue last year.

If it is still an issue, it should be filed on the `request` tracker, because the package has a new maintainer.

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.

For future reference: This issue was solved in `plz` (https://github.com/alphapapa/plz.el), and then fixed in`request` as well.  See: https://github.com/tkf/emacs-request/issues/202
