### ISSUE TITLE
Potentially useful example code

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/matrix-client.el#28]
Just stumbled upon this: https://github.com/lokedhs/potato-emacs/blob/master/potato.el  It's not for Matrix, but I'm guessing it solves some similar issues around implementing a client UI, so it might be useful for us.

**Comment by eqyiel** [comment]
@alphapapa @jgkamat have you guys ever used Circe?  If not, `lui.el` (linewise user interface) may be interesting to you: https://github.com/jorgenschaefer/circe/blob/master/lui.el

**Comment by alphapapa** [comment]
https://github.com/jgkamat/matrix-client-legacy-el/issues/15  :)

**Comment by eqyiel** [comment]
I see you are already on to it!

**Comment by alphapapa** [comment]
This might also be useful, for tracking whether a buffer is visible, so we know whether to issue a notification and update the last-seen line: https://github.com/10sr/switch-buffer-functions-el

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
