### ISSUE TITLE
Can matrix-client support Org link like supported link type `irc:` in Org?

### ISSUE THREAD

**Issue by stardiviner** [alphapapa/matrix-client.el#58]
RT.
I can open `irc://irc.freenode.net/#emacs` in Org Mode link. I hope can do similar thing for Matrix link.

**Comment by jgkamat** [comment]
How would this exactly be handled? I think you could do whatever you want by
configuring `browse-url'.

stardiviner writes:

**Comment by alphapapa** [comment]
Basically you just need to call the join command with the room alias.  It should be simple to define a custom Org link type for that.

**Comment by stardiviner** [comment]
Don't know what does it looks like, can you give out an example?
For example, here is my custom Org link support for `geo:` links.
```lisp
;;; `geo:'
;; [geo:37.786971,-122.399677;u=35]
(defcustom org-geo-link-application-command "gnome-maps"
  "Specify the program name for openning geo: link."
  :type 'string)

(defun org-geo-link-open (uri)
  "Open Geography location `URI' like \"geo:25.5889136,100.2208514\" in Map application."
  (if (executable-find "gnome-maps")
      (start-process
       "org-geo-link-open"
       "*org-geo-link-open*"
       org-geo-link-application-command
       (shell-quote-wildcard-pattern uri))
    (browse-url uri))
  )

(org-link-set-parameters "geo" :follow #'org-geo-link-open)
```

**Comment by alphapapa** [comment]
This seems to work for me:
```el
(defun org-matrix-link-open (room-id)
  "Open Matrix ROOM-ID in `matrix-client'."
  (matrix-join-room (car matrix-client-sessions) room-id))

(org-link-set-parameters "matrix" :follow #'org-matrix-link-open)
```

**Comment by stardiviner** [comment]
Does the `matrix-join-room` support auto detect and connect to matrix server if Emacs does not have connected session yet?

**Comment by stardiviner** [comment]
I tried following Org link formats:
```
[[matrix:#Emacs:matrix.org][#Emacs:matrix.org]]
[[matrix:#Emacs]]
[[matrix:Emacs]]
```
None of them works.
