### ISSUE TITLE
server read as password

### ISSUE THREAD

**Issue by nico202** [alphapapa/matrix-client.el#75]
https://github.com/alphapapa/matrix-client.el/blob/3a149d9bbcce82127c1d954a26bd401816ba5778/matrix-client.el#L156

It should be `read-string` probably

**Comment by alphapapa** [comment]
Thanks.

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
