### ISSUE TITLE
Problem with some character in password

### ISSUE THREAD

**Issue by rfauvet** [alphapapa/matrix-client.el#77]
Hello,
First thank you for maintaining this packages, I just installed it today. However I had a small problem my password was containing special characters like : " è à. This led to a "Login failed : error nil" error. 

I "fixed" it by just changing my password to something without those characters and now it works.

**Comment by alphapapa** [comment]
Hi,

Thanks for reporting.  It's probably a Unicode string encoding issue.  I'll look into it sometime.

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
