### ISSUE TITLE
Installation steps for spacemacs

### ISSUE THREAD

**Issue by Soundtoxin** [alphapapa/matrix-client.el#78]
Is there any chance you could make some installation steps specifically for spacemacs? I tried and failed to follow both the "Quelpa" and "Manually" methods to get this going. I don't really know what I'm doing here, so for now I'm just going to put my configs back to how they were before and give up.

**Comment by Soundtoxin** [comment]
I think I've actually figured it out. Here are some rough steps I wrote out that could be refined if you'd like to add them to the readme.

- I open my spacemacs config with `spc-f-e-d`
- I add `quelpa-use-package` to the following line so that it is installed from MELPA.

   `dotspacemacs-additional-packages '(quelpa-use-package)`

- I require `quelpa-use-package` and paste the recommended lines from the readme in to my `user-config` section.

```
(defun dotspacemacs/user-config ()
(require 'quelpa-use-package)
(use-package matrix-client
  :quelpa ((matrix-client :fetcher github :repo "alphapapa/matrix-client.el"
                          :files (:defaults "logo.png" "matrix-client-standalone.el.sh"))))
  )
```

- I save the file with :w and then reload it with `spc-f-e-R`

On the homescreen I see the following near the top:
```
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: matrix-client@dotfile... [1/1]
Package matrix-client is unavailable. Is the package name misspelled?
```

`Error in dotspacemacs/user-config: Cannot open load file: No such file or directory, matrix-client`

I also see this near the bottom:
```
Found 1 new package(s) to install...
--> installing package: quelpa-use-package@dotfile... [1/1]
```

Many `matrix-` functions now show up in helm when I press `spc-spc` and type matrix.

**Comment by jgkamat** [comment]
Bradley Haggerty writes:

> I tried and failed to follow both the "Quelpa" and "Manually" methods to get
> this going.

What happened?

**Comment by jgkamat** [comment]
Bradley Haggerty writes:

> I think I've actually figured it out. Here are some rough steps I wrote out that could be refined if you'd like to add them to the readme.

I don't think that spacemacs specific installation guides are normally
included for packages, there are <n> emacs distributions out there with <n>
different ways of installing packages, we can't support all of them.

> --> installing package: matrix-client@dotfile... [1/1]
> Package matrix-client is unavailable. Is the package name misspelled?

It sounds to me like for some reason quelpa-use-package isn't installed when
that line runs. I'm not familiar with spacemacs at all though.

**Comment by alphapapa** [comment]
Spacemacs is Emacs.  If you have to do something special to make something work in Spacemacs, that's a Spacemacs issue.

IOW, Spacemacs is great, but issues like this are why some people choose not to use it.  It tries to force configuration into its own system.  You will need to seek help from other Spacemacs users.
