### ISSUE TITLE
Cache token with "secrets" package

### ISSUE THREAD

**Issue by Stebalien** [alphapapa/matrix-client.el#81]
This way, the secret tokens can be stored in the system keyring, pass, etc.

See: https://www.gnu.org/software/emacs/manual/html_mono/auth.html

**Comment by alphapapa** [comment]
This is easier said than done.  See https://www.reddit.com/r/emacs/comments/8lvda6/is_authsource_from_the_dark_side/ and https://www.reddit.com/r/emacs/comments/8dqump/riot_support_in_emacs/dxx69wg/

**Comment by Stebalien** [comment]
Hm. Yeah, that API does look like a pain to deal with. There should just be a simple "put value, get value" interface...

**Comment by alphapapa** [comment]
:)  If/when Emacs gains a better API, I'll be glad to use it here.
