### ISSUE TITLE
Assuming server is matrix.org

### ISSUE THREAD

**Issue by divansantana** [alphapapa/matrix-client.el#93]
When connecting, it prompts for server. I give it `matrix.org` it then
connects but the echo area says "Assuming server is matrix.org". It's
minor, but it shouldn't say "Assuming server is matrix.org" when one
has explicitly giving it the server address.

**Comment by alphapapa** [comment]
Yeah, that code should be rewritten sometime.  It was a hacky solution.

**Comment by ChrisCochrun** [comment]
I've had this happening to me today trying to log in using my own matrix instance.

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
