### ISSUE TITLE
Missing if-let* macro in Emacs 25

### ISSUE THREAD

**Issue by technomancy** [alphapapa/matrix-client.el#94]
I'm not sure when the `if-let*` macro was added, but I'm running Emacs 25 (which matrix-client.el claims to be compatible with) and it doesn't have this macro. Should the requirements be bumped to 26, or should the code get rewritten to use regular `if-let`? (There are only 3 uses that aren't already compatible with `if-let`.)

**Comment by alphapapa** [comment]
Hi,

Thanks for reporting.  Yeah, I haven't used Emacs 25 in quite a while, and there was some back-and-forth in Emacs 26 regarding renaming that macro and changing the binding forms.  We already have to make some aliases: https://github.com/alphapapa/matrix-client.el/blob/0bd5c197b8f67e4467d6d8822301b42497f52a42/matrix-client.el#L41-L44

I'd be glad to just change them to use `-if-let*` (the dash.el macro), which would workaround the problem, but I don't know if the rest of the code is still compatible with Emacs 25.  I'm guessing there would be several other issues, and I'm not that interested in adding more workarounds to keep compatibility with Emacs versions beyond 26.

Would you be able to replace the `if-let*`'s with `-if-let*` and see if the package works?  If so, I'll gladly make those changes.  If that uncovers more compatibility issues, well, we can talk about them, anyway.  :)

Thanks.

**Comment by technomancy** [comment]
I've tested the fix in #96 and it allows Emacs 25 to connect to my homeserver; unfortunately I haven't been able to debug the federation issues I've been seeing with my homeserver, so there may be other problems in functionality I haven't been able to test yet.

**Comment by alphapapa** [comment]
Thank you.  If you don't mind, I'd prefer to wait until it's confirmed to work with Emacs 25 before I merge these changes.  I suspect other changes will be required as well.

**Comment by technomancy** [comment]
That's fine; I realized the server I had set up wasn't going to work
since the packages for synapse in Raspbian are too old and Matrix
themselves don't package for arm, so I am in no hurry.

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
