### ISSUE TITLE
Invalid URL generated for file links when using a non-HTTPS Matrix server

### ISSUE THREAD

**Issue by gergelypolonkai** [alphapapa/matrix-client.el#98]
When i use an HTTP matrix server, URLs generated for file links look like

    https://http//my-matrix.host/_matrix/media/v1/download/sender-host/filename

**Comment by alphapapa** [comment]
Thanks, I guess that should be easy to fix.

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
